-- MySQL Script generated by MySQL Workbench
-- 03/23/17 11:54:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Persönlichkeiten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persönlichkeiten` (
  `Pers_ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Kurzbeschreibung` VARCHAR(255) NULL,
  `Zitat` VARCHAR(45) NULL,
  `Langer Text` VARCHAR(255) NULL,
  `Biografische Daten` VARCHAR(150) NULL,
  `Freischaltung` TINYINT(1) NULL,
  PRIMARY KEY (`Pers_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medien` (
  `Med_ID` INT NOT NULL AUTO_INCREMENT,
  `Typ` VARCHAR(45) NULL,
  `Dateipfad` VARCHAR(45) NULL,
  `Urheber` VARCHAR(45) NULL,
  `Erscheinungsdatum` VARCHAR(45) NULL,
  `Freischaltung` TINYINT(1) NULL,
  `Persönlichkeiten_Pers_ID` INT NOT NULL,
  PRIMARY KEY (`Med_ID`, `Persönlichkeiten_Pers_ID`),
  INDEX `fk_Medien_Persönlichkeiten1_idx` (`Persönlichkeiten_Pers_ID` ASC),
  CONSTRAINT `fk_Medien_Persönlichkeiten1`
    FOREIGN KEY (`Persönlichkeiten_Pers_ID`)
    REFERENCES `mydb`.`Persönlichkeiten` (`Pers_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Geographisch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Geographisch` (
  `Graph_ID` INT NOT NULL AUTO_INCREMENT,
  `Beschreibung` VARCHAR(45) NULL,
  `Ort` VARCHAR(45) NULL,
  `Land` VARCHAR(45) NULL,
  PRIMARY KEY (`Graph_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Werke`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Werke` (
  `Werk_ID` INT NOT NULL AUTO_INCREMENT,
  `Typ` VARCHAR(45) NULL,
  `Dateipfad` VARCHAR(45) NULL,
  `Urheber` VARCHAR(45) NULL,
  `Erscheinungsdatum` VARCHAR(45) NULL,
  `Freischaltung` TINYINT(1) NULL,
  `Geographisch_Graph_ID` INT NOT NULL,
  PRIMARY KEY (`Werk_ID`, `Geographisch_Graph_ID`),
  INDEX `fk_Werke_Geographisch1_idx` (`Geographisch_Graph_ID` ASC),
  CONSTRAINT `fk_Werke_Geographisch1`
    FOREIGN KEY (`Geographisch_Graph_ID`)
    REFERENCES `mydb`.`Geographisch` (`Graph_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kategorien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kategorien` (
  `Kat_ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Unterkategorie` VARCHAR(45) NULL,
  `Beschreibung` VARCHAR(255) NULL,
  PRIMARY KEY (`Kat_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admins` (
  `idAdmins` INT NOT NULL AUTO_INCREMENT,
  `Benutzername` VARCHAR(45) NULL,
  `Passwort` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`idAdmins`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Epochen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Epochen` (
  `E_ID` INT NOT NULL AUTO_INCREMENT,
  `Start` VARCHAR(45) NULL,
  `Ende` VARCHAR(45) NULL,
  PRIMARY KEY (`E_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Werke_has_Persönlichkeiten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Werke_has_Persönlichkeiten` (
  `Werke_Werk_ID` INT NOT NULL,
  `Persönlichkeiten_Pers_ID` INT NOT NULL,
  PRIMARY KEY (`Werke_Werk_ID`, `Persönlichkeiten_Pers_ID`),
  INDEX `fk_Werke_has_Persönlichkeiten_Persönlichkeiten1_idx` (`Persönlichkeiten_Pers_ID` ASC),
  INDEX `fk_Werke_has_Persönlichkeiten_Werke1_idx` (`Werke_Werk_ID` ASC),
  CONSTRAINT `fk_Werke_has_Persönlichkeiten_Werke1`
    FOREIGN KEY (`Werke_Werk_ID`)
    REFERENCES `mydb`.`Werke` (`Werk_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Werke_has_Persönlichkeiten_Persönlichkeiten1`
    FOREIGN KEY (`Persönlichkeiten_Pers_ID`)
    REFERENCES `mydb`.`Persönlichkeiten` (`Pers_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persönlichkeiten_has_Kategorien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persönlichkeiten_has_Kategorien` (
  `Persönlichkeiten_Pers_ID` INT NOT NULL,
  `Kategorien_Kat_ID` INT NOT NULL,
  PRIMARY KEY (`Persönlichkeiten_Pers_ID`, `Kategorien_Kat_ID`),
  INDEX `fk_Persönlichkeiten_has_Kategorien_Kategorien1_idx` (`Kategorien_Kat_ID` ASC),
  INDEX `fk_Persönlichkeiten_has_Kategorien_Persönlichkeiten1_idx` (`Persönlichkeiten_Pers_ID` ASC),
  CONSTRAINT `fk_Persönlichkeiten_has_Kategorien_Persönlichkeiten1`
    FOREIGN KEY (`Persönlichkeiten_Pers_ID`)
    REFERENCES `mydb`.`Persönlichkeiten` (`Pers_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persönlichkeiten_has_Kategorien_Kategorien1`
    FOREIGN KEY (`Kategorien_Kat_ID`)
    REFERENCES `mydb`.`Kategorien` (`Kat_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persönlichkeiten_has_Epochen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persönlichkeiten_has_Epochen` (
  `Persönlichkeiten_Pers_ID` INT NOT NULL,
  `Epochen_E_ID` INT NOT NULL,
  PRIMARY KEY (`Persönlichkeiten_Pers_ID`, `Epochen_E_ID`),
  INDEX `fk_Persönlichkeiten_has_Epochen_Epochen1_idx` (`Epochen_E_ID` ASC),
  INDEX `fk_Persönlichkeiten_has_Epochen_Persönlichkeiten1_idx` (`Persönlichkeiten_Pers_ID` ASC),
  CONSTRAINT `fk_Persönlichkeiten_has_Epochen_Persönlichkeiten1`
    FOREIGN KEY (`Persönlichkeiten_Pers_ID`)
    REFERENCES `mydb`.`Persönlichkeiten` (`Pers_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persönlichkeiten_has_Epochen_Epochen1`
    FOREIGN KEY (`Epochen_E_ID`)
    REFERENCES `mydb`.`Epochen` (`E_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Epochen_has_Kategorien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Epochen_has_Kategorien` (
  `Epochen_E_ID` INT NOT NULL,
  `Kategorien_Kat_ID` INT NOT NULL,
  PRIMARY KEY (`Epochen_E_ID`, `Kategorien_Kat_ID`),
  INDEX `fk_Epochen_has_Kategorien_Kategorien1_idx` (`Kategorien_Kat_ID` ASC),
  INDEX `fk_Epochen_has_Kategorien_Epochen1_idx` (`Epochen_E_ID` ASC),
  CONSTRAINT `fk_Epochen_has_Kategorien_Epochen1`
    FOREIGN KEY (`Epochen_E_ID`)
    REFERENCES `mydb`.`Epochen` (`E_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Epochen_has_Kategorien_Kategorien1`
    FOREIGN KEY (`Kategorien_Kat_ID`)
    REFERENCES `mydb`.`Kategorien` (`Kat_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
